name: dentix
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `fvm flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  # UI
  flutter_svg: ^2.2.4
  path_drawing: ^1.0.1
  intl_phone_number_input: ^0.7.5

  # state management
  get_it: ^9.2.1
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.3

  # Image
  image_picker: ^1.2.1
  file_picker: ^10.3.10
  cached_network_image: ^3.4.1

  # File
  path_provider: ^2.1.5

  # Permissions
  permission_handler: ^12.0.1

  # Storage
  get_storage: ^2.1.1

  # Database
  drift: ^2.31.0
  sqlite3: ^2.9.4
  path: ^1.9.1

  # Router
  go_router: ^17.1.0
  go_transitions: ^0.8.3

  # Tools
  xml: ^6.6.1
  shimmer: ^3.0.0
  share_plus: ^12.0.1
  url_launcher: ^6.3.2

  flutter_local_notifications: ^20.1.0

  open_file: ^3.5.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.31.0
  build_runner: ^2.12.2

  # custom_lint: ^0.7.6
  # riverpod_lint: ^2.6.5
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4
  # fvm dart run flutter_launcher_icons:generate
  # fvm dart run flutter_launcher_icons

  rename_app: ^1.6.5
  # fvm dart run rename_app:main all="Dentix"

  intl_utils: ^2.8.11
  # fvm dart run intl_utils:generate

  flutter_native_splash: ^2.4.7
  # fvm dart run flutter_native_splash:create

  dependency_validator: ^5.0.4
  # https://pub.dev/packages/dependency_validator
  # fvm dart run dependency_validator
  # flutter pub outdated

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/empty_state/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300

  # https://fonts.google.com/noto/specimen/Noto+Sans+Arabic

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: images.dart
  classname: AppImages
  ignore_comments: true
  field_prefix:

flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: ar # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/core/locale # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/core/locale/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false

# C:\Users\isa\AppData\Local\Pub\Cache\bin\fvm flutter build windows --release